### ISSUE TITLE
HAProxy implementation

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/gp-load-balancer#1]
Implement a load balancer using HAProxy.
Configure that HAProxy instance to support: https://glasswallsolutions.com.glasswall-icap.com/ i.e. it will forward the traffic to that website, please take note that https://glasswallsolutions.com.glasswall-icap.com/ setup might has additional domains.

**Comment by svf97** [comment]
Hello,

- do we a have ssl crt (.pem file)
- may i have servers IPs?

**Comment by svf97** [comment]
Hello, 
Please verify if the backend IP address required for this task is 54.78.209.23 as I get the following error:
> Note: setting global.maxconn to 524270.
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result FAILED
Total: 3 (2 usable), will use epoll.
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
Using epoll() as the polling mechanism.
[WARNING] 307/174834 (11188) : Server backendnodes/node1 is DOWN, reason: Layer4 timeout, check duration: 2001ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[NOTICE] 307/174834 (11188) : haproxy version is 2.2.4-de45672
[NOTICE] 307/174834 (11188) : path to executable is /usr/local/sbin/haproxy
[ALERT] 307/174834 (11188) : backend 'backendnodes' has no server available!

Please find attached the configuration file for this issue:

```
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    #ca-base /etc/ssl/certs
    #crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL). This list is from:
    #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
    # An alternative list with additional directives can be obtained from
    #  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
    #ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    #ssl-default-bind-options no-sslv3

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http

frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance source
    option forwardfor
    option httpchk
    http-request set-header X-Forwarded-Port %[dst_port]
    #http-request add-header X-Forwarded-Proto https if { ssl_fc }
    http-check send meth HEAD uri / ver HTTP/1.1 hdr Host localhost
    server node1 54.78.209.23:9999 check


listen stats
    bind :32700
    stats enable
    stats uri /
    stats hide-version
    stats auth someuser:password

```

**Comment by mahnouman** [comment]
@svf97 The IP is correct, it is what https://glasswallsolutions.com.glasswall-icap.com/ resolves to. But I do not think that this 9000 port in the config file is relevant at all, we are running http and https , this is 80 and 443

**Comment by mahnouman** [comment]
Hello @naderaly just an update about the issue, what we need to create here is a HAProxy setup for the websites itself, so for example we will have something like:
User ---> HAPRoxy-website ----> Squid ---> glasswallsolutions.com

**Comment by naderaly** [comment]
@mahnouman I've created a PR with the documentation for installation, configuration & exporting the haproxy OVA to work as a LB for the target website (glasswallsolutions.com.glasswall-icap.com)
https://github.com/k8-proxy/GW-proxy/pull/128 
Also the OVA is exported and ready to be uploaded on S3 & I've asked an assist from the team to do so as I dont have access

**Comment by naderaly** [comment]
Is There any specific files I should push to our current repository ?
