### ISSUE TITLE
Custom HAProxy ICAP healthcheck

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/gp-load-balancer#14]
Referencing [How to write an external health check script for HAProxy](https://www.loadbalancer.org/blog/how-to-write-an-external-custom-healthcheck-for-haproxy/):

Please create a custom health check for HAProxy to detect if an ICAP server is still processing files or down.

**Comment by mahnouman** [comment]
@naderaly please lead the development of this, and get help from @haitham911 on the usage of C-ICAP-Client since he was experimenting with it and also if you need to create a Golang script.

**Comment by haitham911** [comment]
@mahnouman 
@GINAGC 
I have sent a PR please merge

**Comment by mahnouman** [comment]
@Mehasseb please contact both @haitham911 and @naderaly to do a functionality test to the script.

**Comment by mahnouman** [comment]
Hello @naderaly please test and integrate the application layer health check code into a new instance of the load balancer, configured to the same backend servers as the "all" LB, you can use a small instance of that load balancer because it will be just for the sake of testing the app layer health checks, set the health checks to intervals of 30 seconds. Thank you.

Hello @haitham911 please check the Lambda functions and try to convert this code into one.
