### ISSUE TITLE
Loadbalance ICAP servers

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/gp-load-balancer#3]
Initially trying this out with HAProxy, we need to create a HAProxy instance using the minimum resources to load balance two ICAP servers already deployed:
icap01.glasswall-icap.com	54.155.107.189
icap02.glasswall-icap.com	34.240.204.39

A guideline is provided here:
https://support.kaspersky.com/KWTS/6.1/en-US/167740.htm

**Comment by mahnouman** [comment]
Hello @svf97 please work with Nader on this task jointly.

**Comment by naderaly** [comment]
Updated README file with required steps, Also posted HAProxy configuration file
